config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'footprints#index'
  resources :footprints, only: [:index, :show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/footprint.rb
class Footprint < ApplicationRecord

  before_update do
    recalculate_footprint
  end

  belongs_to :user

  validates :duration_on_terminal, presence: true
  validates :terminal_category, presence: true
  validates :data_size, presence: true
  validates :country, presence: true
  validates :data_size, numericality: { greater_than_or_equal_to: 0 }
  validates :duration_on_terminal, numericality: { greater_than_or_equal_to: 0 }

  private

  def recalculate_footprint
    if self.country == "France"
      area = 59
    elsif self.country == "USA"
      area = 447
    else
      area = 596
    end

    if self.terminal_category == "phone"
      terminal = 1.1**-4
    else
      terminal = 3.2**-4
    end
    self.carbon_footprint = self.data_size * (7.2**-11 + 1.52**-10)* 59 + self.duration_on_terminal * terminal * area * self.additional_factor
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :footprints
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization


  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/footprints_controller.rb
class FootprintsController < ApplicationController
  before_action :set_footprint, only: %i[show]

  def index
    @footprints = policy_scope(Footprint)
  end

  def new
    @footprint = Footprint.new
    authorize @footprint
  end

  def create
    @footprint = Footprint.new(footprint_params)
    @footprint.user = current_user
    authorize @footprint

    if @footprint.save
      @footprint.carbon_footprint = recalculate_footprint
      @footprint.save
      redirect_to @footprint, notice: 'Your digital carbon footprints has been created'
    else
      render :new
    end
  end

  def show
  end

  private

  def set_footprint
    @footprint = Footprint.find(params[:id])
    authorize @footprint
  end

  def footprint_params
    params.require(:footprint).permit(:duration_on_terminal, :terminal_category, :data_size, :country)
  end

  def recalculate_footprint
      if @footprint.country == "France"
        area = 59
      elsif @footprint.country == "USA"
        area = 447
      else
        area = 596
      end

      if @footprint.terminal_category == "phone"
        terminal = 1.1**-4
      else
        terminal = 3.2**-4
      end
      @footprint.carbon_footprint = @footprint.data_size * (7.2**-11 + 1.52**-10)* 59 + @footprint.duration_on_terminal * terminal * area * @footprint.additional_factor
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/footprints_helper.rb
module FootprintsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/footprints/_form.html.erb
<%= simple_form_for(@footprint) do |f| %>
  <%= f.label :duration_on_terminal_in_minutes %>
  <%= f.number_field :duration_on_terminal %>
  <%= f.input :terminal_category, collection: ["Phone", "Computer"] %>
  <%= f.input :country, collection: ["France", "USA", "China"] %>
  <%= f.label :data_size_in_kilooctet %>
  <%= f.number_field :data_size %>
  <%= f.submit class: "btn-gradient" %>
<% end %>

app/views/footprints/index.html.erb
<div class="container">
  <div></div>
  <div class="title text-center d-flex justify-content-between align-items-center mt-5">
    <% if current_user && current_user.footprints.any? %>
      <%= link_to "Log out", destroy_user_session_path, :method => :get, :class => "btn-ghost" %>
      <% if current_user.admin == true %>
        <%= link_to "Admin", "/admin", :class => "btn-ghost" %>
      <% end %>
      <%= link_to "calculate another carbon footprint", new_footprint_path, :class => "btn-flat" %>
      <h1 class="">Welcome</h1>
      <h1>Please find below all your digital carbon footprint:</h1>
    <% else %>
    <% if current_user.admin == true %>
      <%= link_to "Admin", "/admin", :class => "btn-ghost" %>
    <% end %>
    <%= link_to "calculate your carbon footprint", new_footprint_path, :class => "btn-flat" %>
    <% end  %>
  </div>
  <div class="" >
    <% current_user.footprints.each_with_index do |footprint, index| %>
      <div class="">
        <h3><%= index + 1 %> - <strong>Total Carbon Footprint:</strong> <%= footprint.carbon_footprint.round(3) %> KgCo2</h3>
        <% if footprint.terminal_category == "Computer"  %>
        <p>A good way to reduce your carbon footprint would be to use phone instead of your computer </p>
        <% end  %>
        <%= link_to "See datas", footprint_path(footprint[:id]), :class => "btn-flat" %>
      <% end %>
  </div>
</div>

<div class="tips">
  <h2>Please find below our tips to reduce your digital carbon footprint:</h2>
  <ul>
    <li>Keep as long as possible your digital equipments</li>
    <li>Chose refurbished instead of brand new equipment</li>
    <li>Uninstall useless software, they are slowing down your machine</li>
    <li>Put your computer in sleep mode after 3 minutes of inactivity</li>
    <li>Avoid sending too many emails with too heavy files attached</li>
    <li>Sort often your emails</li>
  </ul>
</div>

app/views/footprints/new.html.erb
<%= link_to "Back", footprints_path %>

<div class="container">
  <%= render "form", footprint: @footprint %>
</div>

app/views/footprints/show.html.erb
<div class="container">
  <h1 class="fw-bold">Please find below all the data you picked for this calculation :</h1>

  <h2><strong>Total time on terminal (min):</strong> <%= @footprint.duration_on_terminal %> </h2>
  <h2><strong>Terminal Type:</strong> <%= @footprint.terminal_category %></h2>
  <h2><strong>Datas weight (Ko):</strong> <%= @footprint.data_size %></h2>
  <h2><strong>Country:</strong> <%= @footprint.country %></h2>
  <% if @footprint.additional_factor > 1.0 %>
  <h2><strong>additional factor:</strong> <%= @footprint.additional_factor %></h2>
  <% end %>
  <h2><strong>Total carbon footprint:</strong> <%= @footprint.carbon_footprint.round(3) %> KgCo2</h2>
  <%= link_to "Back", footprints_path, :class => "btn-gradient" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DigitalFootprint</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <div>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>